/** IPC channel names (PRD §7). Dependency-free so the sandboxed preload can bundle it. */
export const IPC = {
  // capture window -> main
  audioChunk: 'audio:chunk',
  audioLevel: 'audio:level',
  captureStatus: 'capture:status',
  // main -> capture window
  captureStart: 'capture:start',
  captureStop: 'capture:stop',
  captureMic: 'capture:mic',
  // main -> windows
  transcriptUpdate: 'transcript:update',
  sessionState: 'session:state',
  debugLatency: 'debug:latency',
  uiNavigate: 'ui:navigate',
  settingsChanged: 'settings:changed',
  // main -> overlay (answers)
  questionDetected: 'question:detected',
  answerToken: 'answer:token',
  answerDone: 'answer:done',
  answerError: 'answer:error',
  qaReset: 'qa:reset',
  overlayNav: 'overlay:nav',
  overlayFocusAsk: 'overlay:focusAsk',
  screenPending: 'screen:pending',
  overlayNotice: 'overlay:notice',
  hotkeysStatus: 'hotkeys:status',
  costUpdate: 'cost:update',
  // main window -> main (invoke)
  sessionStart: 'session:start',
  sessionStop: 'session:stop',
  settingsGet: 'settings:get',
  settingsSet: 'settings:set',
  apiKeySet: 'settings:setApiKey',
  apiKeyStatus: 'settings:apiKeyStatus',
  overlayToggle: 'overlay:toggle',
  mainToggle: 'main:toggle',
  appQuit: 'app:quit',
  // any window -> main (invoke)
  answerNow: 'answer:now',
  answerRegenerate: 'answer:regenerate',
  answerShorter: 'answer:shorter',
  answerAsk: 'answer:ask',
  voiceAskSet: 'voice:set',
  qaList: 'qa:list',
  profileGet: 'profile:get',
  profileSave: 'profile:save',
  profileImportResume: 'profile:importResume',
  screenCapture: 'screen:capture',
  screenAdd: 'screen:add',
  screenAnswer: 'screen:answer',
  screenClear: 'screen:clear',
  screenDisplays: 'screen:displays',
  costGet: 'cost:get',
  costOpenPricing: 'cost:openPricing',
  historyList: 'history:list',
  historyGet: 'history:get',
  historyDelete: 'history:delete',
  historyDeleteAll: 'history:deleteAll',
  historyExport: 'history:export',
  // practice mode (main window -> main invoke; state is pushed main -> main window)
  practiceState: 'practice:state',
  practiceStart: 'practice:start',
  practiceRecord: 'practice:record',
  practiceFinishAnswer: 'practice:finishAnswer',
  practiceSubmit: 'practice:submit',
  practiceRetry: 'practice:retry',
  practiceRedo: 'practice:redo',
  practiceSkip: 'practice:skip',
  practiceNext: 'practice:next',
  practiceFinish: 'practice:finish',
  practiceReset: 'practice:reset',
  // work mode: project store (main window -> main invoke; changes pushed main -> windows)
  workProjects: 'work:projects',
  workProjectsChanged: 'work:projectsChanged',
  workProjectSave: 'work:projectSave',
  workProjectDelete: 'work:projectDelete',
  workTaskSave: 'work:taskSave',
  workTaskDelete: 'work:taskDelete',
  workUpdateAdd: 'work:updateAdd',
  workUpdateDelete: 'work:updateDelete',
  // work mode: status quick-pick (main -> overlay) and the pick (overlay -> main)
  workPick: 'work:pick',
  workStatus: 'work:status',
  // work mode: updates from Teams (FR-T1..T4) — import, review queue
  workImport: 'work:import',
  workProposals: 'work:proposals',
  workProposalsChanged: 'work:proposalsChanged',
  workProposalDecide: 'work:proposalDecide',
  // work mode: Teams sync (FR-T3)
  teamsStatus: 'teams:status',
  teamsSignIn: 'teams:signIn',
  teamsOpenSignIn: 'teams:openSignIn',
  teamsCancelSignIn: 'teams:cancelSignIn',
  teamsSignOut: 'teams:signOut',
  teamsSources: 'teams:sources',
  teamsSyncNow: 'teams:syncNow',
  // app
  appDeleteAllData: 'app:deleteAllData',
  appInfo: 'app:info'
} as const
